# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

#definitions:
#  steps:
#    - &cache
#      name: Cache multiple paths
#      uses: actions/cache@v2
#      with:
#        path: |
#          ~/cache
#          !~/cache/exclude
#          **/node_modules
#          **/.cache/yarn
#          /usr/local/share/.cache/yarn
#          /var/lib/docker/overlay2
#        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [10.x, 12.x, 14.x]
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
#        <<: *cache
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
            **/.cache/yarn
            /usr/local/share/.cache/yarn
            /var/lib/docker/overlay2
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build:test
      - run: yarn start:github
      - run: MIRTH_HOST=$(yarn findMirth)
      - run: yarn setupMirth:action
      - run: yarn test:action