# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [10.x, 12.x, 14.x]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
          **/.cache/yarn
          /usr/local/share/.cache/yarn
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn install
        yarn build:test
        yarn start:github
        docker ps
        docker logs dockerfiles_mirth_1
        sleep 30
        curl http://localhost:8080
        docker logs dockerfiles_mirth_1
        yarn setupMirth:container
        docker ps
        yarn test:container